### ISSUE TITLE
Suggestion: add reference & on inout and out direction for parameters

### ISSUE THREAD

**Issue by R2RT** [staruml/Cpp#15]
Title ;)
And if it's possible, out could be marked as /* [OUT] */ in declaration.

Eg.
foo(out x:int, inout y:double, inout data:byte[*])
turns to:
void foo(/* [OUT] */ int& x, double& y, std::vector<byte>& data);

**Comment by R2RT** [comment]
After all, I've implemented it by myself. Can't push it to repo, so here is file:
[CppCodeGenerator.zip](https://github.com/staruml/Cpp/files/60589/CppCodeGenerator.zip)

**Comment by niklauslee** [comment]
Thank you for your suggestion and contribution. But we don't know this feature will be liked by the most of users. We want to wait merge this feature until there is enough agreements from the users. Finally, please use pull-request if you want to contribute to this project. You can find more information about pull-request at https://help.github.com/articles/using-pull-requests/.
