### ISSUE TITLE
Typo in README.md: it said C# instead of C++

### ISSUE THREAD

**Issue by meisyal** [staruml/Cpp#16]
Hello, StarUML.

I found there was a mistaken word in `README.md` file. The mistaken word is `C#` in line 97. It says:

> 2. Select a folder containing C# source files to be converted to UML model elements.`

instead of

> 2. Select a folder containing C++ source files to be converted to UML model elements.`

Sorry if I don't make a pull request because it's just a typo.

**Comment by niklauslee** [comment]
Thank you for reporting an issue. It has fixed.
