### ISSUE TITLE
Cannot install C++ extension on Widows XP

### ISSUE THREAD

**Issue by yogesh4ever** [staruml/Cpp#9]
I am using staruml V2.0.0-beta11.
In installation guide following path is mentioned to unzip c++ extension
'C:\Users\<user>\AppData\Roaming\StarUML\extensions\user' 

As I am using winsows XP I don't have the above path in the system.
I used to unzip at 'C:\Documents and Settings\yrz910432\Application Data\StarUML\extensions\user'

But the extension is not present in the Menu->Tools->.
How to resolve the problem

Regards,
Yogesh

**Comment by niklauslee** [comment]
Please update to recent version (v2.0.1)
